### ISSUE TITLE
Alert won't close when back button pressed

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla#116]
Friend. Select one friend. Delete this friend. Then, a sweet alert popped up.

Now, press back button on your phone. The alert won't close but the page history go back.

**Comment by Anduin2017** [comment]
@ganlvtech This issue has been resolved and merged to `dev` branch. You can try this feature in `staging.kahla.app`. When we are about to release the `2.2.0` version of Kahla and this issue will be automatically be resolved.

Thanks for your feedback again!
