### ISSUE TITLE
Use history replace instead of history push on some action

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla#119]
- [x] back button on should use `history.back()`.
- [x] physical back button (back button provided by phone, browser or <kbd>Alt</kbd>+ <kbd>Left</kbd>) should behave similar with back button on UI.
- [x] switch between 3 tab of the home page should use `history.replaceState`.
- [x] sign out should clear history stack, to prevent user go back to loggin-only page.
- [x] (for PWA only) back on home page must close the app, this means whenever you are at home page of the app, history stack must only have one item.

These are only suggestions. It may be solve by some other solution or tricks.

**Comment by Anduin2017** [comment]
@ganlvtech This issue has been resolved and merged to `dev` branch. You can try this feature in `staging.kahla.app`. When we are about to release the `2.2.0` version of Kahla and this issue will be automatically be resolved.

Thanks for your feedback again!
