### ISSUE TITLE
Not auto scroll to the end until pictures finish loading.

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla#137]
1. Clear browser cookie and storage.
2. Open a conversation or group, which contains large pictures in recent messages.

You will find page will not scroll to the end, until these pictures finish their loading.

**Comment by xxyzz** [comment]
That's a feature 😂

**Comment by ganlvtech** [comment]
@xxyzz
So would this 'feature' be fixed or changed?

**Comment by Anduin2017** [comment]
For pics loads slow now. I suggest to trigger scrolling after all messages loads not all pics.

**Comment by Anduin2017** [comment]
@xxyzz You wanna handle this?

**Comment by Anduin2017** [comment]
While loading the talking page, all media resources shall be a loading image. And the page shall directly scroll to the bottom while the media resources are loading.

After loading all those media resources it may be seconds later. The position of the page may not be far from the previous position. And shall not move the page nor trigger any other events.

The loading pic shall like this:

 ![loading](https://demo.bopoda.cn/images/video-default.png)

This is my design. Any suggestions?

**Comment by XiangruiKong2019** [comment]
44

**Comment by XiangruiKong2019** [comment]
6666

**Comment by Anduin2017** [comment]
Feature restored in pull request #146
