### ISSUE TITLE
HTML tag not escaped. inject avaliable

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla#139]
Directly input:

```html
<img src="https://example.com/example.jpg">
<img src="data:...">
<video src="https://example.com/example.mp4">

<h1>h1</h1>
<h2>h2</h2>

<b>bold</b> <i>italic</i> <em>emphasis</em> <strong>strong</strong>

<font color="red">red</font> <font size="9">big</font>

<i class="fa fa-address-book"></i>
```

**Comment by xxyzz** [comment]
Well...I trust Angular's sanitization: https://angular.io/guide/security#angulars-cross-site-scripting-security-model And the purpose of binging message content to `innerHTML` is to convert links to `<a>` tag, so the user can click the shared links.

**Comment by ganlvtech** [comment]
Yes. XSS seems not available. But class attribute and font tag should be striped, or messages will go messy.

**Comment by Anduin2017** [comment]
Fixed in `dev` branch.
