### ISSUE TITLE
Upload file extension not support upper case

### ISSUE THREAD

**Issue by ganlvtech** [AiursoftWeb/Kahla#180]
https://github.com/AiursoftWeb/Kahla.App/blob/fa8f8718d100f816eca1a35282c790dce713f94a/src/app/Services/UploadService.ts#L143-L160

Uploading `1.jpg` is OK, but I cannot upload files such as `1.JPG`.

By the way, the code might not the best way to test file extension.

**Comment by Anduin2017** [comment]
Good issue indeed. How about using `Trim` and `ToLower` method to make it better? @xxyzz
