### ISSUE TITLE
Open some page in default browser

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#204]
https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl

When there was a new version in Kahla, we need to open the download page.

When the user sends a link and other users click it, we need to open it.

In that cases, if Kahla is running in electron it will open the page in electron, not in the default browser. That was not expected.

**Comment by ganlvtech** [comment]
You can have a try to drag a url to electron. It will go to that page. This is really common if you using default setting for electron.

**Comment by Anduin2017** [comment]
The integrated browser in electron seems very weak. That it even could not download the latest Kahla App. So we have to use the default browser to open it.
