### ISSUE TITLE
Kahla don't load friend requests count in conversations page.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#217]
Kahla don't load friend requests count in conversations page.

**Comment by xxyzz** [comment]
I just tried, it works well...

**Comment by Anduin2017** [comment]
Repro steps:

* Create account A
* Create account B
* Send a new friend request to A as B
* Sign out B
* Sign in A

Expected

```
Display a red dot on the `friends` tab.
```

Happened

```
No red dot on the `friends` tab until I click it.
```
