### ISSUE TITLE
Display the users' primary email in his profile page.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#224]

**Comment by Anduin2017** [comment]
Ohhh, I mean, display the email of the person you are viewing. Not only your own email. For users' primary email is public and we usually need that to verify his identity.

I guess we can add a `Validated` badge on his email if his email was validated by us so that user can trust the conversation.

**Comment by Anduin2017** [comment]
@ganlvtech @l2dy How do you like that?

**Comment by l2dy** [comment]
> Ohhh, I mean, display the email of the person you are viewing. Not only your own email. For users' primary email is public and we usually need that to verify his identity.

Primary email should not be made public by default, we have enough spam in our mailboxes already. It can be made opt-in though.

**Comment by Anduin2017** [comment]
Agree. So we can make it a switchable option that if the user wanna make his primary email public.

**Comment by Anduin2017** [comment]
@l2dy Your opinion was rejected and now the user has to set at least one Email to `public` or he won't be able to use Kahla. For primary Email is always public in Aiursoft.

Maybe we will design email address protection system in the future but for now, we need to open all primary emails and users know that.

**Comment by Anduin2017** [comment]
I have modified our Kahla API that supports to set if the user wanna hides his primary email in Kahla.

By default, that option was true which means that his email was open to everyone. The same design with GitHub.

The user shall be able to update his profile settings to hide his primary email. If he changed that option, everywhere the server returns the object of the user will hide his email.

https://wiki.aiursoft.com/ReadDoc/Kahla/Auth.md#UpdateInfo

**Comment by l2dy** [comment]
> By default, that option was true which means that his email was open to everyone. The same design with GitHub.

AFAIK, GitHub enables email privacy by default.
