### ISSUE TITLE
Hi, could you support Chinese language?

### ISSUE THREAD

**Issue by yunjuanai** [AiursoftWeb/Kahla#245]
试用了一下非常喜欢，想推荐给家人用，可以加个简体中文皮肤吗？

**Comment by Anduin2017** [comment]
Good idea. Under consideration now.

**Comment by Anduin2017** [comment]
This issue is under consideration for Kahla is not supported in China.

**Comment by Anduin2017** [comment]
The Chinese government doesn't allow chat app without tracking.

See here: http://www.cac.gov.cn/2019-04/16/c_1124373996.htm
