### ISSUE TITLE
Scroll issue in cordova app

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#246]
The scrolling logic seems to be strange in talking page of Kahla cordova app.

**Comment by Anduin2017** [comment]
@xxyzz  I found that it seems the talking page scroll issue also occurs in Microsoft Edge. Is that the same reason?

**Comment by xxyzz** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions), Edge doesn't  support `ScrollToOptions`. This dictionary is used at [`UploadService.ts` line 153](https://github.com/AiursoftWeb/Kahla.App/blob/master/src/app/Services/UploadService.ts#L153). Chrome for Android is full support.
