### ISSUE TITLE
learn

### ISSUE THREAD

**Issue by github-bigang** [AiursoftWeb/Kahla#256]
learn

**Comment by Anduin2017** [comment]
Please describe what you want.

There are many ways to contribute to the project: logging bugs, submitting pull requests, reporting issues, and creating suggestions.

Even if you have push rights on the repository, you should create a personal fork and create feature branches there when you need them. This keeps the main repository clean and your personal workflow cruft out of sight.

We're also interested in your feedback for the future of this project. You can submit a suggestion or feature request through the issue tracker. To make this process more effective, we're asking that these include more information to help define them more clearly.
