### ISSUE TITLE
Firefox can not sign out.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#277]
1. Download Firefox (with passing the GFW).
2. Sign in.
3. Go to `Devices` and found that the current device was not added.
4. Sign out, and you will find that you can not sign out now!

**Comment by xxyzz** [comment]
Request `/fontawesome-webfont.woff2` get 404, so service worker doesn't install. But the `.woff` file exists.

**Comment by Anduin2017** [comment]
Ok. Please try adding a new rule to this file so that the web server returns `woff2`.

https://github.com/AiursoftWeb/Kahla.App/blob/master/src/web.config

And merge it to try again.
