### ISSUE TITLE
Don't send message again with meaningful server response.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#292]
What the hell is the message resend system? When did we develop it? Shall we drop it?

**Comment by xxyzz** [comment]
If send message get an error it will try to resend later. That's quite useful, isn't it?
It resides in [here](https://github.com/AiursoftWeb/Kahla.App/blob/master/src/app/Services/InitService.ts#L129) and [here](https://github.com/AiursoftWeb/Kahla.App/blob/master/src/app/Controllers/talking.component.ts#L178), added in this [commit](https://github.com/AiursoftWeb/Kahla.App/commit/7dc91fd391539fd79c6eb36d9d7a955082404087).

**Comment by Anduin2017** [comment]
Yeah. That seems to be useful when the network works badly. But if the service successfully gets a server response, I mean even 500 error response, shall not send the message again.

Only resend messages when 503 error or other network issues. For meaningful server response, don't send it again.
