### ISSUE TITLE
Image may displays huge.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#308]
# Repro step

1. download [this](https://oss.aiursoft.com/download/fromkey/4113)
2. Send it in one conversation.
3. That displays huge!

**Comment by xxyzz** [comment]
Can't reproduce...

**Comment by Anduin2017** [comment]
Emmmm....

What did you see then?

**Comment by xxyzz** [comment]
Just a normal image...but longer 
<img width="433" alt="Screen Shot 2019-03-13 at 14 10 08" src="https://user-images.githubusercontent.com/21101839/54257296-d5c0b580-4599-11e9-947e-426122a1cc90.png">
<img width="1439" alt="Screen Shot 2019-03-13 at 14 10 38" src="https://user-images.githubusercontent.com/21101839/54257314-e2dda480-4599-11e9-8c95-0c9f15f834f3.png">

**Comment by Anduin2017** [comment]
Yeah. That was the issue. It shall be such long. It looks annoying, especially on desktop browsers.

What's your idea? Shall we fix it?

**Comment by xxyzz** [comment]
Leave it be...If scale on height, it will not be readable. Or set a max picture height and scale again, but I think the current scale setting base on width is fine.

**Comment by Anduin2017** [comment]
Ok.

**Comment by Anduin2017** [comment]
I have reconsidered this issue. Our image viewing experience is good on mobile devices. But on the desktop, sending large images may ruin a conversation.
