### ISSUE TITLE
Open links in default browser on electron edition of Kahla.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#315]
Open links in default browser on electron edition of Kahla.

When sending links in Kahla and click it, the page was opened in Kahla. I guess it was not valid.

The link shall be open in default browser.

**Comment by Anduin2017** [comment]
@hv0905  I was about to close this, but another error occurs

Repro steps:

* Staging Env
* Dev Branch
* 3.0.2
* Electron build

![Screenshot (187)](https://user-images.githubusercontent.com/19531547/54406623-22cd9480-471e-11e9-9da3-a6fc92bde016.png)


Just install and double click the app.

**Comment by hv0905** [comment]
Oh...It seens there are some problem in package-lock.json.. I will fix it later.

**Comment by Anduin2017** [comment]
It seems that @xxyzz  has another solution now. He told me that his solution works better and don't require any other 3rd-party libraries. 

I will ask him later.

**Comment by Anduin2017** [comment]
His solution is similar with this one

https://github.com/AiursoftWeb/Kahla.App/pull/312/files

**Comment by hv0905** [comment]
Yeah using `ngx-electron` to open shell might be a better solution. Nice.
