### ISSUE TITLE
Design a e2e encrypt algorithm

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#34]

**Comment by Anduin2017** [comment]
In my opinion, we should do this work in several steps. After which step the app is runnable and users will continue to be able to chat. After the entire migration process, the app is entirely e2e encrypted.

**Comment by Anduin2017** [comment]
Great plan. I will work on the API part.

**Comment by Anduin2017** [comment]
I have successfully finished the first step in the following commits:

- https://github.com/AiursoftWeb/AiursoftOnContainers/commit/a9bbd48796275e983d5a23bb1ff41c3f72f144ab
- https://github.com/AiursoftWeb/AiursoftOnContainers/commit/05d003e07c859a5db41f19eb746cb405e5e3fbbf

And I have successfully finished the second step in the following commits:

- https://github.com/AiursoftWeb/Kahla.App/commit/df72a28d90631b42fcbc1fb3832de6d0a6b53d32
- https://github.com/AiursoftWeb/Kahla.App/commit/b5a5963c4d1c93a2be4cfa57cf821a3fec8c2a1a
- https://github.com/AiursoftWeb/Kahla.App/commit/99cdb793643b6826341d054c0109df8f7e5f7a21
- https://github.com/AiursoftWeb/Kahla.App/commit/f54c9818b0001f7e8496b8a1f214605fa5101514

And I have allowed sending files and images via the encrypted method:

https://github.com/AiursoftWeb/Kahla.App/commit/dd352752d08ce0261a2766ea6d3ad6273108e42a

What do you think of this design? @l2dy 

Please review those changes and give any advice.

**Comment by l2dy** [comment]
If the server has direct access to the session keys used for private conversations, the purpose of E2EE is completely defeated. How do you plan to encrypt the session/conversation key on the server side?

**Comment by Anduin2017** [comment]
My first design is to use the user's password as a key to encrypt the PSK. So that all conversations and message history would be synced to new devices as he signs in immediately.

**Comment by BigSnow1** [comment]
Now that you have implemented AES encryption, it's time for us to continue down the road. Next, we need to apply RSA encryption algorithm between client and server. This means that each device will generate a pair of RSA key pairs. For example, device A wants to communicate with device B. When A and B establish a friend request, they exchange their public keys. If A sends a message to B, A needs to first encrypt the message with B's public key, then encrypt it with AES, send it to the server, and then the server sends it to B. In this process, AES encryption is used to communicate between server A and server B, and the server cannot decrypt RSA-encrypted messages, ensuring end-to-end features. What do you think about my idea?

**Comment by Anduin2017** [comment]
Yeah. Like Signal app. Per conversation per key.

**Comment by l2dy** [comment]
Do you plan to authenticate the messages?

**Comment by Anduin2017** [comment]
Currently no. Only encrypt the messages.

**Comment by BigSnow1** [comment]
I think it is feasible to encrypt symmetric encryption keys with a password.

**Comment by Anduin2017** [comment]
Good idea. But you need to verify that per password could generate a unique key pair. Please first create an example project with node.js and publish it to Github.com. So that we could see if that algorithm work.

**Comment by l2dy** [comment]
First, a quote from "A Formal Security Analysis of the Signal Messaging Protocol", emphasis mine.

> Recent revelations about mass interception and surveillance of communications have made consumers more privacy-aware. In response, scientists and developers have proposed techniques which can provide security for end users **even if they do not fully trust the service providers**.

@BigSnow1:

> generates an RSA key pair based on the password

How?

>  Also use the public key of another user of the session to encrypt the AES key and insert it into the database.

Are we going to implement group chats? If so, what about new members of a group chat? In particular, what happens when a compromised server adds a fake member to the conversation?

> the server has no original AES key

For each new conversation, the server may secretly keep the key. This doesn't fit @Anduin2017's threat model, in which conversation keys may only be exposed to the server upon user login.

**Comment by BigSnow1** [comment]
First of all, the idea of using a password to generate a key pair is still under study, and no ready-made algorithms can be used. If you have any good way to provide to me, I would greatly appreciate it. This process is done so that messages can be synchronized across devices.
Second, you may have misunderstood my expression. Sometimes my expression is not accurate. I am sorry. What I want to express is that the AES key needs to be encrypted by the public keys of the two parties of the conversation, respectively, and it is saved separately and inserted into the conversation database table. The reason for doing this is to keep a copy of the AES key on the server but do not want the server to know the original key.
As for the group conversation, there are still many problems. At present, I just want to complete the end-to-end private conversation.

**Comment by l2dy** [comment]
> generates an RSA key pair based on the password

Note that if a user changes his password, all session keys have to be re-encrypted. Should this be done by the server or the client?

Compared to using the password to encrypt the RSA key pair, this solution doesn't scale well.

> the server will generate AES key

That means a malicious server can secretly keep the session keys.

**Comment by Anduin2017** [comment]
> the server will generate AES key

I don't think that the final edition has to let the server do it. Any Kahla client could generate the AES key and pass it to the partner device.

**Comment by BigSnow1** [comment]
This design has the problem you said. Using the  password to generation key is for synchronization across device messages, but changing the password cause another problem. It is difficult to achieve the best of both worlds. It is very difficult to use end-to-end implementations where it is possible to change passwords at will and to synchronize messages across devices.  Unless this idea is abandoned. Do you have any good ideas?

**Comment by Anduin2017** [comment]
> generates an RSA key pair based on the password

That was where her algorithm most unpredictable part. I have seen no library or API to achieve that. So I suggest verifying this was feasible first.

**Comment by l2dy** [comment]
You can use the password to encrypt the account's private key, and use this account key to encrypt session keys. So when password is changed only the account key needs to be re-encrypted, not all session keys.

**Comment by Anduin2017** [comment]
> Recent revelations about mass interception and surveillance of communications have made consumers more privacy-aware. In response, scientists and developers have proposed techniques which can provide security for end users even if they do not fully trust the service providers.

I have a question. Our current design allows the server to touch users password. But the server only calculates the password hash and compare it with hash in the database. Is this a "A Formal Security" design?

**Comment by l2dy** [comment]
@Anduin2017 I don't think you'll use [formal methods](https://en.wikipedia.org/wiki/Formal_methods) in this project.

**Comment by Anduin2017** [comment]
At least user will submit his password to the server to sign in. At least the server could access the user's password when the user is signing in. So Kahla will never be absolutely secure or 'formally design'. 

Our current issue is only trying to make Kahla server more difficult to decrypt the messages. And our first target is:

**Even if the entire Kahla database was opened to the public, hackers could get no message.**

But the current code on master branch was not achieved that target.

**Comment by l2dy** [comment]
> At least the server could access the user's password when the user is signing in.

No, see SRP (Augmented PAKE).

**Comment by l2dy** [comment]
> Even if the entire Kahla database was opened to the public, hackers could get no message.

Only data in the DB being compromised is a relatively narrow case.

After you deployed a "secure" protocol, updating it (to make it more secure) would require migration, which may become a pain and cause loss of user data. That's why I'm trying to enforce a relatively high standard on our protocol.

**Comment by Anduin2017** [comment]
Yeah. I understand. Kahla's target is not absolutely secure but relative secure and for better performance and user experience. We will reconsider its final target. The issue will be temporarily closed.
