### ISSUE TITLE
App could not auto update

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#345]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: 1817520
- Platform: `PWA`
- Browser: `Chrome`

## How to repro

- Step 1: Pin 3.1.0 to the home screen.
- Step 2: Wait for 3.1.1 release.
- Step 3: Try refreshing.

And then the app was not upgraded and still 3.1.0. No matter how many times I refresh. I even tried uninstalling the Kahla PWA app and reinstall it. Still 3.1.0

## Expected situation

I expect that the app could be upgraded to 3.1.1.

## Other information

Is there something wrong with our service worker?

**Comment by xxyzz** [comment]
I think we should add `cache-control` and `expires` headers to the kahla.app server. Although the service worker tries to fetch after using the cached files, it gets them from the browser disk cache.
<img width="1323" alt="Screen Shot 2019-03-23 at 09 21 55" src="https://user-images.githubusercontent.com/21101839/54859870-46f82980-4d4d-11e9-87e9-9dbf5222c2b9.png">
