### ISSUE TITLE
Right to be forgotten

### ISSUE THREAD

**Issue by l2dy** [AiursoftWeb/Kahla#354]
## Describe the solution you'd like

1. Support deleting individual messages.
2. Support clearing chat history.
3. Support deleting an account.

**Comment by Anduin2017** [comment]
Will resolve.

**Comment by xxyzz** [comment]
Please also consider removing the tracker, I hate trackers.

**Comment by Anduin2017** [comment]
> Please also consider removing the tracker, I hate trackers.

There is no tracker on `Kahla.App` and `Kahla.Server`. Consider opening an issue on `Kahla.Home` please.
