### ISSUE TITLE
design contrtibution

### ISSUE THREAD

**Issue by masudr4n4** [AiursoftWeb/Kahla#42]
want to make a  logo for this project.if  you have any requirements then let me know .its free for any open sourrce projects.

**Comment by Anduin2017** [comment]
Oh, thank you so much. Feeling so happy that someone really wanna help. But unfortunately, Kahla currently already has its own logo here: https://github.com/AiursoftWeb/Kahla.App/tree/master/src/assets.

If you have any better ideas, just create any pull requests and replace those files. Thanks a lot!

Or the issue will be closed in several days later.

**Comment by masudr4n4** [comment]
yah sorry for that.actually i have not founded the logo by mistake.old one is awsome  for this  projects.dont mind pls.
