### ISSUE TITLE
Request for kahla group chat support to set group manager administrator group member

### ISSUE THREAD

**Issue by Xiangrui2019** [AiursoftWeb/Kahla#430]
## Describe the solution you'd like
I want kara to support group chat setting group member group manager administrator

## Describe alternatives you've considered
Nothing.

**Comment by hv0905** [comment]
I think we have to think it over because we have to change a lot in Kahla Backend.

**Comment by Xiangrui2019** [comment]
emmm.

**Comment by Xiangrui2019** [comment]
我自己解决这个问题吧， 你们别搞了

**Comment by Anduin2017** [comment]
Under consideration.
