### ISSUE TITLE
The user will become a ghost after leaving a group.

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#436]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `all`
- Last git commit: `a3351d0`
- Platform: `any`
- Browser: `chrome`

## How to repro

- Step 1: Create a new group and leave the talking page opened.
- Step 2: Open a new web browser and then use another account to join the group just created.
- Step 3: Send some messages in the second user.
- Step 4: Leave the group.
- Step 5: Back to the first user, **clear the browser cache in F12** and then refresh the page.
- Step 6: You can see the avatar of the second user is always loading and the nickname of it is always `New User`.

## Expected situation

I expect that the message should be deleted or display the correct sender.

## Other information

Nothing.

**Comment by Anduin2017** [comment]
Ok. I will try to find a solution to fix this.

**Comment by Xiangrui2019** [comment]
Solution to this problem: Just check whether the sender of each message is in the group at a time.

Of course, if there are still some optimizations in this method, please point out them.


```

var messagesprocessed = [];

for (var message in messages) {
    for (var user in group.users) {
       if (message.senderid == user.id) {
            messagesprocessed.append(message);
       }
    }
}
```

**Comment by Xiangrui2019** [comment]
I'm thinking about the way that I don't need to create new arrays. Please don't implement this way first.

**Comment by Anduin2017** [comment]
Disappearing directly may cause the conversation context unreadable. How about adding the sender's info to the message context? Which means every message will be returned with its sender context info. @xxyzz  This makes the app's logic easier and simpler. But larger JSON.

If we still could not find a better solution, I will append that.

**Comment by Xiangrui2019** [comment]
Do not create new arrays, only through the original array operation to achieve functions

**Comment by Xiangrui2019** [comment]
No, don't let this disappear directly. Vanishing will cause a lot of strange problems. I'm going to change its display name to a name called "Out of Group Chat" and keep the message below.

**Comment by Xiangrui2019** [comment]
```
for (var message in messages) {
    for (var user in group.users) {
       if (message.senderid != user.id) {
            message.sender.nikename = "Out of Group Chat";
            message.sender.headimg = "Find a picture with a cross number and put it on it.";
       }
    }
}
```

Second, the solution, thanks to Daniel's guidance, does not have these problems, nor does it need to create new arrays.

**Comment by Xiangrui2019** [comment]
```javascript
for (var message in messages) {
    for (var user in group.users) {
       if (message.senderid != user.id) {
            message.sender.nikename = "Out of Group Chat";
            message.sender.headimg = "Find a picture with a cross number and put it on it.";
       }
    }
}
```

**Comment by hv0905** [comment]
My solution is calling `userDetail` every time we couldn't find a user in `MessageService.users`. However, I'm not sure if this will cause a lot of extra calls of `userDetail` if there are a lot of ghosts in a group.

**Comment by Anduin2017** [comment]
@hv0905 I will try returning user's info along-side the message.

**Comment by Anduin2017** [comment]
https://github.com/AiursoftWeb/Kahla/pull/77

These changes on the server-side make this issue more easy to fix.
