### ISSUE TITLE
Can not insert an AT in the middle of the sentence.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#444]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging`
- Last git commit: 7acf6f3aab3c9e11e5faff38b3443d8fcce38432
- Platform: `Web Desktop\Web Mobile\Electron\Cordova\PWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

- Step 1: Go to a group conversation.
- Step 2: Type a sentence.
- Step 3: Insert an `@` in the middle of the sentence.

And then I can't at someone.

## Expected situation

I expect that I can at someone.

## Other information

Nothing.

**Comment by Xiangrui2019** [comment]
Solutions to this problem:

```javascript
message.split(' ').forEach((s, index) => {
            if (s.length > 0 && s.includes('@')) {
                console.log(s);
                const searchResults = this.searchUser(s.slice(1));
                if (searchResults.length > 0) {
                    atUsers.push(searchResults[0][0]);
                    newMessageArry[index] = `<a class="chat-inline-link atLink" data-userid="${searchResults[0][0]}"
href="/user/${searchResults[0][0]}">${newMessageArry[index]}</a>`;
                }
            }
        });
```

`Hello @Anduin Xue Bugs At Half Past Five @/ Hello`
Just add a space in the middle of the message and at.

**Comment by Xiangrui2019** [comment]
jhhh@xxx

**Comment by Xiangrui2019** [comment]
对了，github @不加空格也不生效

**Comment by Xiangrui2019** [comment]
By the way, github@doesn't work without spaces.

**Comment by Xiangrui2019** [comment]
Sorry, I say Chinese.

**Comment by Anduin2017** [comment]
It seems that this issue was not fixed and still could repro in the staging env.
