### ISSUE TITLE
Some text on friends page seems ugly and hard to read

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#473]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: 524b4a735aad6f33d0d4b7809b476ab31b61f154
- Platform: `Web Desktop\Web Mobile\Electron\Cordova\PWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

- Step 1: Sign in Kahla
- Step 2: Use a light theme
- Step 3: Go to the `friends page` or the  `requests page`.

And then some text seems not clear and hard to read.

![Untitled](https://user-images.githubusercontent.com/19531547/57606000-83e8db80-759a-11e9-855e-8ada874dac82.png)

## Expected situation

I expect that different theme shall use a different text color.

## Other information

Nothing.

**Comment by hv0905** [comment]
I think we should simplify our theming file because there are TONS of gray colors in the theming file.
