### ISSUE TITLE
Couldn't auto refresh after verify E-mail 

### ISSUE THREAD

**Issue by ghost** [AiursoftWeb/Kahla#475]
Couldn't auto refresh after verify E-mail.(P1.2)
![1](https://user-images.githubusercontent.com/30626271/57854883-e00e6280-781b-11e9-81d8-6cc8044e2f7a.png)

![2](https://user-images.githubusercontent.com/30626271/57855377-16001680-781d-11e9-96ba-4ebcfc2fd15a.png)
 I need to restart the Kahla to refresh or I couldn't add the friends.(P3)
![3](https://user-images.githubusercontent.com/30626271/57855169-9eca8280-781c-11e9-92ca-04048e48f3bc.png)

I think we can add a button in on P4 to check account verify or not.
![4](https://user-images.githubusercontent.com/30626271/57855265-d1747b00-781c-11e9-81b7-7d80b6bce56e.png)

（PS：我英语好蹩脚啊QWQ

**Comment by Anduin2017** [comment]
That was really strange. It seems that the server did not refresh the latest email status from `api.aiursoft.com`.

BTW, calling this API will refresh the email confirmation status: https://wiki.aiursoft.com/ReadDoc/Kahla/Auth.md#Me

It seems that the app side shall call this when the user is clicking the warning.

**Comment by hv0905** [comment]
@Anduin2017 It's strange to require a `Me` api call for updating the email status. So what about updating it in Kahla backend, [here](https://github.com/AiursoftWeb/Kahla/blob/dev/Kahla.Server/Controllers/GroupsController.cs#L83)

**Comment by Anduin2017** [comment]
Only `ME` API responses if the current user's email is verified. So calling this will always get the latest email status. It is reasonable.

The code you mentioned is not the only place which needs the user's email verification status. Changing all possible places costs a lot of internal communication.

My suggested solution is:

> When the user is pressing the warning button, call `ME` API to get the latest email confirmation status.  If verified, update local app logic. If not, alert.

**Comment by ghost** [comment]
> Only `ME` API responses if the current user's email is verified. So calling this will always get the latest email status. It is reasonable.
> 
> The code you mentioned is not the only place which needs the user's email verification status. Changing all possible places costs a lot of internal communication.
> 
> My suggested solution is:
> 
> > When the user is pressing the warning button, call `ME` API to get the latest email confirmation status.  If verified, update local app logic. If not, alert.

That's what I want to say!
