### ISSUE TITLE
Local connection to kahla's app and server

### ISSUE THREAD

**Issue by BigSnow1** [AiursoftWeb/Kahla#49]
### Versions
```
<!--
Output from: git log -1.
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
The kahla's app and server are copied locally and then I try to connect the app to the local server.  I just changed the address of the app server. The other codes are not changed.  Then, I  run the server side in the command box.  I used two commands: dotnet build and dotnet run.  After that, I run the app in VScode.  However, the browser displays a 404 error.  Why is that?

### Desired behavior
```
<!--
What would like to see implemented?
What is the usecase?
What did you expect to see?
-->
```

**Comment by Anduin2017** [comment]
Please tell us which address returned 404 and try to access it with curl.

If you still could not access the API, please ensure Kahla server was successfully started.

Test the root path for Kahla server and tell us the result.
