### ISSUE TITLE
The talking page screen was not scrolled to the bottom when clicking the input panel.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#491]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: 524b4a735aad6f33d0d4b7809b476ab31b61f154
- Platform: `Cordova apk`
- Browser: `Cordova apk`

## How to repro

- Step 1: Login Kahla.
- Step 2: Go to a talking page with many messages.
- Step 3: Scroll to the bottom
- Step 4: Tap the input panel

And then the talking page will scroll to the top immediately.

## Expected situation

I expect that that talking page shall scroll to the bottom smoothly.

## Other information

Nothing.

**Comment by xxyzz** [comment]
I have no idea why it scroll to the top...

**Comment by Anduin2017** [comment]
Maybe some API is not useable in Cordova. Could you please try to investigate which one calls differently from the browser?
