### ISSUE TITLE
Can not send image

### ISSUE THREAD

**Issue by Wenfengcheng** [AiursoftWeb/Kahla#498]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: Production
- Platform: Web Desktop
- Browser: Chrome

## How to repro

- Step 1: 
send image and repro it

And then nothing happened

## Expected situation

I expect that image can be sent correctly!

**Comment by Anduin2017** [comment]
Seems strange. Can not repro now. It may be a network issue.

**Comment by Anduin2017** [comment]
@AiursoftWeb/kahla-team  Please keep this issue open for 2 weeks. And close it if we couldn't repro this same strange issue again.

**Comment by Anduin2017** [comment]
The issue was found again by Kahla user `zealot killer`. And I have handled the server response with: "Please provide a file."

It seems that Kahla was possible in some condition that doesn't submit the file when setting a new avatar.

@xxyzz  Is that?

**Comment by Anduin2017** [comment]
It seems that @EdiWang  reproed this issue again but no accurate evidence.

**Comment by hv0905** [comment]
This issue seems has been fixed in #563 and #567

**Comment by Anduin2017** [comment]
Cool!
