### ISSUE TITLE
Change the server database

### ISSUE THREAD

**Issue by BigSnow1** [AiursoftWeb/Kahla#50]
### Versions
```
<!--
Output from: git log -1.
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3
If I want to change the kahla server's database to sqlite locally, I need to change which files and what changes can be made. The more detailed the better.

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
```
<!--
What would like to see implemented?
What is the usecase?
What did you expect to see?
-->
```

**Comment by Anduin2017** [comment]
The issue was closed for lack of description. Please fill the form and submit again.
