### ISSUE TITLE
Wide Screen Support

### ISSUE THREAD

**Issue by Elic0e** [AiursoftWeb/Kahla#501]
Support the wider screen can improve the user experience at PC or Tablet devices.

**Comment by Anduin2017** [comment]
Under consideration.

**Comment by Anduin2017** [comment]
![Untitled](https://user-images.githubusercontent.com/19531547/59186960-d374f400-8ba6-11e9-80ef-515850dcd686.png)

A preview for an ideal design. Love this? @hv0905 

I have tried implementing this before but found it too hard and gave up.

**Comment by hv0905** [comment]
@Anduin2017 @xxyzz What about this implement? This makes Anduin's design easy to achieve.
![image](https://user-images.githubusercontent.com/29349119/59553034-f39b1d80-8fc1-11e9-926d-73614fa45a41.png)

**Comment by Anduin2017** [comment]
My idea is to make:

* Some components can only be placed left. Like `conversations`, `friends`, `me`, `search` which displays less data or displays a list of selectable choice.
* The other components can only be placed right. If it can not be determined, just display a logo.
* There shall always be a reasonable component in the left. But maybe empty in the right.
* On small devices, the logic remains the same with the current design.

<img width="856" alt="Annotation 2019-06-17 014351" src="https://user-images.githubusercontent.com/19531547/59567628-a80c7080-90a2-11e9-9829-d0265506767f.png">
<img width="858" alt="Annotation 2019-06-17 014633" src="https://user-images.githubusercontent.com/19531547/59567629-a93d9d80-90a2-11e9-92a3-76e37a6fed52.png">
<img width="854" alt="Annotation 2019-06-17 014737" src="https://user-images.githubusercontent.com/19531547/59567630-aa6eca80-90a2-11e9-9bdf-70615d037a20.png">
<img width="856" alt="Annotation 2019-06-17 014840" src="https://user-images.githubusercontent.com/19531547/59567632-ab9ff780-90a2-11e9-844a-85a9b9cfe232.png">
<img width="859" alt="Annotation 2019-06-17 014905" src="https://user-images.githubusercontent.com/19531547/59567634-ae025180-90a2-11e9-8beb-307aa15e1ab3.png">
<img width="856" alt="Annotation 2019-06-17 014934" src="https://user-images.githubusercontent.com/19531547/59567635-afcc1500-90a2-11e9-993e-9fb5e7d55881.png">
<img width="856" alt="Annotation 2019-06-17 015003" src="https://user-images.githubusercontent.com/19531547/59567638-b195d880-90a2-11e9-9a6d-15d981fbef15.png">
<img width="853" alt="Annotation 2019-06-17 015026" src="https://user-images.githubusercontent.com/19531547/59567642-b2c70580-90a2-11e9-9471-ead7aa831b60.png">
