### ISSUE TITLE
Notification button display is abnormal

### ISSUE THREAD

**Issue by DeusSeuca** [AiursoftWeb/Kahla#504]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production(Kahla-3.4.0-win.zip)`
- Last git commit: `f8e09f09a4f916ea50dd63618942db3c6fb071c6`
- Platform: `Web Desktop`
- Browser: `Others`

## How to repro

- Step 1:Ensure that group notifications are opened 
- Step 2: Join group chat(Anduin-Bilibili)
- Step 3: Click on the top right button(Three-person Icon)
Or click the notification button quickly

And then...<What happened?>
Notification button display is abnormal.
![GIF](https://user-images.githubusercontent.com/38712063/58783679-14ec2900-8614-11e9-8c25-50a7ff2b30fc.gif)

## Expected situation
Just submit bug

## Other information

Nothing.

**Comment by Anduin2017** [comment]
Thanks! Will resolve.

**Comment by Anduin2017** [comment]
It seems that the same issue happens in the hide email settings part. We will keep diagnosing this.

**Comment by hv0905** [comment]
I can't repro this after a lot of times of tries in Web browser and Electron App.....
