### ISSUE TITLE
How to create RSA key pair based on password?

### ISSUE THREAD

**Issue by BigSnow1** [AiursoftWeb/Kahla#51]
**Is your feature request related to a problem? Please describe.**
How to create RSA key pair based on password?
Tell me your ideas!
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Anduin2017** [comment]
This is an issue about some knowledge that has nothing to do with the current project. You should first search the internet or talk with me privately but not submitting an issue here.

Kahla issue part is only for following statements:

- Bug
- Suggestion
- Feature request
- Question about the project itself
- Obsolete
- Performance
- Security
