### ISSUE TITLE
Kahla web page cannot accept friend messages

### ISSUE THREAD

**Issue by jianba** [AiursoftWeb/Kahla#510]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging(Pre-release)\Production`
- Last git commit: `aaaaaa`
- Platform: `Web Desktop\Web Mobile\Electron\Cordova\PWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

 Kahla web page cannot accept friend messages

## Expected situation

I expect that this problem can be solved

## Other information

Nothing.

**Comment by Anduin2017** [comment]
Ok. We will try to investigate this.
