### ISSUE TITLE
Space between words

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/Kahla#52]
Versions: 1.1.0 Alpha

### Observed behavior
![screenshot from 2018-08-09 14-20-10](https://user-images.githubusercontent.com/21101839/43881626-5efe8bca-9bdf-11e8-8f40-0159babfba09.png)
![screenshot from 2018-08-09 14-21-02](https://user-images.githubusercontent.com/21101839/43881655-7ae9f248-9bdf-11e8-933f-b85c7bb2eeac.png)

### Desired behavior
Show spaces

This bug is caused by font-family inherits from body.

**Comment by Anduin2017** [comment]
Please submit any screenshot.

**Comment by xxyzz** [comment]
Remove "emoji" in font-family should solve this bug.

**Comment by Anduin2017** [comment]
I couldn't repro this issue. Please help me check it and close it.

**Comment by xxyzz** [comment]
Try test in Fedora? I forget which font is rendered and already erased the disk.

**Comment by Anduin2017** [comment]
Ohh. I will close this issue. Maybe someday I will reopen it when I could repro that issue again.
