### ISSUE TITLE
Last Photo Message Unreadable in Conversations Page

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/Kahla#53]
### Versions
1.0.0 Alpha

### Repro steps
Send a photo

### Observed behavior
<img width="484" alt="screen shot 2018-08-09 at 21 56 56" src="https://user-images.githubusercontent.com/21101839/43903516-34fef900-9c1f-11e8-8aac-9e801fa9d8ca.png">

### Desired behavior
Let the user know it's a photo.

### Mention any other details that might be useful (optional)
I didn't realize the default branch is master, so only the last message on the home page is unreadable, the talking page works well.

**Comment by Anduin2017** [comment]
@xxyzz Do you wanna handle it and try to fix it?

**Comment by Anduin2017** [comment]
This was because the 1.1.0 version of Kahla encrypted the message. And I could decrypt it here. So currently I am not planned to fix it.
