### ISSUE TITLE
Failed to parse installation package.

### ISSUE THREAD

**Issue by FNAC-Z** [AiursoftWeb/Kahla#531]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- OS:`Android7.0`
- Device name:`Redmi NOTE 7X`
- MIUI versions:`MIUI10 9.5.23`
- App versions:`3.4.0/3.5.0`

## How to repro

- Step 1: Download the app from release page
- Step 2: click the app to install

And then...<error occurred!>

## Expected situation

I expect that...

## Other information

![12](https://user-images.githubusercontent.com/46148006/59241934-31075000-8c3c-11e9-877b-19d63c941c0b.png)

**Comment by Anduin2017** [comment]
Will resolve.

**Comment by Anduin2017** [comment]
Duplicate with issue: https://github.com/AiursoftWeb/Kahla.App/issues/487
