### ISSUE TITLE
Show an alert message when clicking send test notification in electron.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#539]
## What do you suggest us to do?

When the user clicks the `Send test notification` button in the electron app, nothing happens. That seems strange.

If the trigger device was an electron device, just create a new notification, saying that this is a test message from our push system
So the electron user can easily find that their electron app is notification supported.

## Additional context

Nothing.

**Comment by xxyzz** [comment]
The test message doesn't send a websocket event, and the electron app needs that event to show a notification.

**Comment by Anduin2017** [comment]
Nope, that wasn't related to server. Just create a new notification directly without contacting the server.

**Comment by xxyzz** [comment]
[here?](https://github.com/AiursoftWeb/Kahla/blob/dev/Kahla.Server/Controllers/DevicesController.cs#L134)

**Comment by Anduin2017** [comment]
Ok if changing the server side code will solve this easier.

**Comment by Xiangrui2019** [comment]
stop. not change server. https://developer.mozilla.org/zh-CN/docs/Web/API/notification

**Comment by Anduin2017** [comment]
Please reference this:

https://github.com/AiursoftWeb/Kahla/commit/6fd9dc0d72539db8f1352b95b30b2be8a7119ae3

**Comment by Xiangrui2019** [comment]
yes
