### ISSUE TITLE
The uploader requires refactoring

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#562]
## What do you suggest us to do?

Now that the uploader has a very bad user experience.

The user couldn't know the upload progress.
And the user can't find out if their file was successfully uploaded.

We need to refactor the uploader to support the upload progress.

Please refer to this: [colossus](https://colossus.aiursoft.com)

## Additional context

And We need to show an alert to prevent the user click the upload again.

![image](https://user-images.githubusercontent.com/19531547/60511130-cf4e7900-9d03-11e9-878c-e693b92e5140.png)

**Comment by Anduin2017** [comment]
While the progress issue was fixed, I suggest that we need to show an alert to prevent the user click the upload again and make the progress bar easier to notice.

**Comment by xxyzz** [comment]
Sweetalert seems don't update the progress value, it's always 0.

**Comment by Anduin2017** [comment]
So, how can we prevent the user from uploading a file again?

**Comment by xxyzz** [comment]
I don't think you can... I just don't know how to update the value inside the alert HTML.

**Comment by hv0905** [comment]
@xxyzz you can use `Swal.getContent().querySelector('#id')` to get an element inside sweetalert

**Comment by Anduin2017** [comment]
> @xxyzz you can use `Swal.getContent().querySelector('#id')` to get an element inside sweetalert

So, is this element readonly?

**Comment by hv0905** [comment]
> > @xxyzz you can use `Swal.getContent().querySelector('#id')` to get an element inside sweetalert
> 
> So, is this element readonly?

No, it's just a normal HTML element

**Comment by hv0905** [comment]
> So, how can we prevent the user from uploading a file again?

If we show an alert dialog that can't close manually, the user even can't click the upload button.
But, according to @xxyzz 's word, the dialog which cannot close is annoying sometime, especially when the network is bad.

**Comment by Anduin2017** [comment]
Of course. Closing the dialog shall stop uploading. So it might be difficult to stop uploading.

**Comment by hv0905** [comment]
We can use `unsubscribe` to force stop an existing uploading

**Comment by Anduin2017** [comment]
It seems that the progress number was not shown.
