### ISSUE TITLE
Sound alert on new messages.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#579]
## What do you suggest us to do?

Now that on new notifications, if you are focusing the talking page but doing some stuff on other windows, like playing a game, you won't get any notifications.

If you can play a simple sound like below when on new notifications, (Even when the user is focusing) It will make it less possible to miss new messages.

## Additional context

Sound file:

https://oss.aiursoft.com/ColossusPublic/a2e874964d154405b00978abea67f6c2.mp3?name=a.mp3

**Comment by hv0905** [comment]
After adding the sound effect, I suggest not to show the browser notify when the browser window is not focused.

**Comment by Anduin2017** [comment]
Yeah. The sound effect has the higher privilege. And no matter what cases shall not alert twice.

**Comment by xxyzz** [comment]
We don't need this feature, it's not in the standard, see [here](https://github.com/whatwg/notifications/pull/127).
