### ISSUE TITLE
Issues found in Google Play store version.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#580]
* [x] The icon installed was really ugly.
* [x] Address bar is always showing.
* [ ] No splash screen.
* [x] Can not be searched by searching 'Kahla'.

**Comment by Anduin2017** [comment]
The address bar seems to be solved.

**Comment by Anduin2017** [comment]
The search result seems to be fixed.

**Comment by Xiangrui2019** [comment]
Good. all fixed.
