### ISSUE TITLE
Prevent calling 「getMessages」 and 「All」api to update messages when receiving a new message.

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#589]
## What do you suggest us to do?

I suggest preventing calling `getMessages` and `All`api to update messages when receiving a new message.
This can make it faster to receive the new message, and reduce the load on the server.

## Additional context

Nothing.

- [ ] All
- [x] getMessages

**Comment by Anduin2017** [comment]
Yep. But that seems to be complicated.

We need to consider:

* Conversations order.
* New conversation appeared.
* `At` event yellow dot appear and disappear.
* Red-dot appear and disappear.
* Old conversation disappeared.

**Comment by Anduin2017** [comment]
Hi, how is this issue's progress? Seems we can already cache the `all` API response. But it seems that it still contains many bugs.

Currently, I can not steadily repro any bug. If I found some bug related to this issue, I may respond here.
