### ISSUE TITLE
Connect latest Storage(Probe) API.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#609]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## About the new API

- Provider: `Kahla`

## About the API feature

This API connects to our new storage base: Probe.

## API document address

The document of the API is [here](https://wiki.aiursoft.com/ReadDoc/Kahla/Storage.md)

## Why probe?

Probe is more powerful. Supports multiple sites and folders. Also, Probe does not use the ID to identify files but path instead.

So that different conversations have different folders. And different users have different permissions to access. Which makes files safer to save, and API simpler.

## How to use Probe API?

Probe API returns file path instead of file id.

For example, if you call the [upload media API](https://wiki.aiursoft.com/ReadDoc/Kahla/Storage.md#UploadIcon):

The path server return shall be like:

```
siteName/pathA/pathB/pathC/filename.extension
```

We use the `sitename/path/filename` pattern to represent a file instead of a file ID. You should use this pattern to save and send messages representing files instead of the file id.

## Icon storage

To maintain the users' icon, we used to call the `Me` API. `Me` API now returns `iconFilePath` instead of `headImgFileKey`. So stop using the `headImgFileKey`. Use `iconFilePath` instead.

The property `iconFilePath` will be removed from Kahla server response at the time when all users upgraded to the probe version of Kahla.

## How to download a file

Now as we all know, you can easily get a file represented by `sitename/path/filename`. But you can not download it that way. To download, you need to add some protocol names.

For this situation, just add: 

```
https://probe.aiursoft.com/Download/InSites/{The pattern}
```

For example, if you get a file with the pattern: `mynewsite/img_20190727_143308.jpg` 

* The path of this file is `/`. 
* The site name of this file is `mynewsite`.
* The file name of this file is `img_20190727_143308.jpg`

Add the head `https://probe.aiursoft.com/Download/InSites/`

Get the download address: 

https://probe.aiursoft.com/Download/InSites/mynewsite/img_20190727_143308.jpg

## Message pattern changes

Currently, we are using a file ID to represent a file. For example:

```
[video]12345
```

Now we need to change it to use file path instead. For example:

```
[video]mynewsite/myconversation/img_20190727_143308.jpg
```

Or

```
[file]mynewsite/myconversation/img_20190727_143308.jpg | 10000 (For file size)
```

Or 

```
[img]mynewsite/myconversation/img_20190727_143308.jpg | 80 | 80 (For image size)
```

Encrypt it! Send it! Enjoy!

## Another concept changes

Before, we are using different APIs to upload images and files.

From now, they are all the same! The [Upload File](https://wiki.aiursoft.com/ReadDoc/Kahla/Storage.md#UploadFile) API is used for all images, files, and videos!

For the [Upload icon](https://wiki.aiursoft.com/ReadDoc/Kahla/Storage.md#UploadIcon) API, it is only used for updating the user's head image icon! Do not use it to send messages!

## The way updates the user's profile!

The update profile API has been changed! Now you have to pass the `filePath` instead of the `fileKey`

**Comment by xxyzz** [comment]
Do you mean `headImgFileKey` will be removed? And group seems don't have that path. `ContactInfo` should also include icon path.

**Comment by Xiangrui2019** [comment]
group default image in oss. please anduin upload to probe storage.

**Comment by Anduin2017** [comment]
Will resolve.

**Comment by Anduin2017** [comment]
All conversations API has been changed!

![image](https://user-images.githubusercontent.com/19531547/62509089-6e531d00-b83c-11e9-9a5f-d1c546bbbf09.png)

Now get `all` will return the image path instead of image key.

**Comment by Anduin2017** [comment]
Conversation details API has been changed!

![image](https://user-images.githubusercontent.com/19531547/62509196-d86bc200-b83c-11e9-8c8a-9867027283d1.png)

Now it will return the image path instead of the image key.

**Comment by Anduin2017** [comment]
Search everything API has been changed!

![image](https://user-images.githubusercontent.com/19531547/62509253-0bae5100-b83d-11e9-9811-c7111a4ddd22.png)

Now it will return the image path instead of the image key.

**Comment by Anduin2017** [comment]
Friendship/Mine API has been changed!

![image](https://user-images.githubusercontent.com/19531547/62510028-1fa78200-b840-11e9-92cb-dff8874d43d8.png)

**Comment by Anduin2017** [comment]
Our update group profile API has been changed! 


![image](https://user-images.githubusercontent.com/19531547/62512696-a6ae2780-b84b-11e9-8d0d-455a14ab0770.png)
