### ISSUE TITLE
Suggest the user to pin Kahla to screen.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#611]
## What do you suggest us to do?

Now that Google provides us the API to suggest the user install the Kahla app.

It also supports to detect if the user opens Kahla from his pinned PWA app. So we can prompt the user to pin it.

## Additional context

https://developers.google.com/web/fundamentals/app-install-banners/#show_the_prompt

**Comment by hv0905** [comment]
Do you mean to show a `sweetalert` dialog to notify user to add Kahla to homescreen? This might be annoying sometimes. Or do you have any better solution?

**Comment by Anduin2017** [comment]
Indeed. I am still considering.

**Comment by hv0905** [comment]
What about adding a button on `About` Page?

**Comment by Anduin2017** [comment]
Nice! Just this!
