### ISSUE TITLE
Users' photo isn't displayed

### ISSUE THREAD

**Issue by scottiiwei** [AiursoftWeb/Kahla#617]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: Production
- Last git commit: 15b0ac2
- Platform: Web Desktop(Win 10 64-bit) also on Web Mobile(iphone X IOS12.3.1)
- Browser: Google Chrome(76.0.3809.100 64-bit) and Safari on [iphone]

## How to repro

- Step 1: Click "Me" on bottom
- Step 2: upload a new photo and showed me uploaded successfully
- Step 3: Refresh the page
- Step 4: The photo still cannot displayed on every slides(chatting message, Me and Edit profile slides)

I tried a JPEG image which is 266KB and a PNG image which is 16KB. Both are failed. It happened on Google Chrome(Windows) and IOS safari.

## Expected situation
Hope it is worked.

## Other information

Just one more question. Have you set the default avatar for new users or users who haven't uploaded their avatar yet? If so, the default avatar still cannot show up on my browzer. It showed me a tearing picture. It looks like the image cannot be loaded.

**Comment by scottiiwei** [comment]
By the way, they all happened via web.kahla.app instead of Application on Andraid.

**Comment by Anduin2017** [comment]
Hi, thanks for your feedback!

We are currently upgrading some of our infrastructures and all data was saved to our new basic services. But the traditional Kahla is still using the old API level. Sorry for this interruption.

This issue will be resolved in the next release. The plan is on 8/9/2019.

Your last question: Yes. You have a default avatar if you did not change it. It was just like this:

![imag](https://probe.aiursoft.com/Download/InSites/usericon/default.png)

**Comment by scottiiwei** [comment]
That’s cool. Also there is a bug about message module. It was unable to display the complete messages on iPhone. After opening the keyboard, some messages will stay in the upper right corner of the phone.  And the sliding operation is also invalid. The result is those messages cannot be visually observed. The only way to solve this problem is changing the screen into horizontal screen then change back. This bug will be fixed after this update as well?  Because I have seen that there is an issue about sliding...

**Comment by Anduin2017** [comment]
@hv0905 Can you repro the issue @scottiiwei mentioned? I couldn't repro this. Thanks!

**Comment by scottiiwei** [comment]
Would you mind I talk about this new issue via this link instead of opening a new issue? I just tried 1 min ago. The problem is still existed. I reckon that I need to talk about the issue specificly. I uploaded some images with this comment. 

Problem 1: After I signed in my account, I cannot sliding on screen. Sliding operation is not
worked on "Kahla, Friends and Me" (Please have a look with image 1,2 and3). 
![image 1](https://user-images.githubusercontent.com/53746463/62693658-44555280-ba16-11e9-94ef-bf1a3e59b369.jpg)
![image 2](https://user-images.githubusercontent.com/53746463/62693660-44555280-ba16-11e9-9454-a2e9e39bd1af.jpg)
![image 3](https://user-images.githubusercontent.com/53746463/62693662-44555280-ba16-11e9-8a51-7e6127ac161c.jpg)

Problem 2: I cannot sliding on screen so I cannot do any operation expect click. I clicked into Kahla. Please have a look with first uploaded image 1, you can see the black circle I made that my 2 chatting tabs hiden by the UI and address Bar. It happened after I signed in without any operation. 

Problem 3: In "Friends" div, it also happened that my 2 chatting group tabs have been hiden on the top of divs(please have a look with image 4). And the sliding operation is not worked, so I cannot chat within the group. 
![image 4](https://user-images.githubusercontent.com/53746463/62693689-4ddeba80-ba16-11e9-9f01-a9b495d02c04.jpg)

Further information: I noticed that the only way to solve the problem about Sliding operation failure is turn off portrait orintation lock on my iphone. Then lying down the phone to change it into horizontal display mode. Then change it back to the vertical display.The sliding operation will start working fluently. 

And the problem about the tabs are covered by the address bar and UI, they all happened after login without any operation. All bugs happened on iPhone X IOS12.3.1 via Safari in web.kahla.app.

**Comment by Anduin2017** [comment]
#622 May fix this. But it is still under testing.

**Comment by scottiiwei** [comment]
That’s all good. I haven’t used github before actually. I’m assigned a project by my tutor to redesign a Human participation(blog) webpage. That one is open sourced, built simply and easily...no more freamwork only used JavaScript and HTML(also css). I’m looking for some good project in Typescript. Trying to create some surprises to my tutor...lol...Thank you for ur reply and have a good day. By the way, I hope the day that google could be viewed without VPN in CN. The real reason you know. lol. Don’t forget ur permission :)

**Comment by Anduin2017** [comment]
Hi, this fixed was deployed on our staging environment. Could you please help us to find if this issue was fixed. Thanks!

Staging environment: https://staging.kahla.app

**Comment by scottiiwei** [comment]
Hi. I'm sorry for late reply. I need to say that there are same problems happened in staging environment(staging.kahla.qpp) as well... Some taps covered by the address bar, UI and divs in Safari. Plus, the sliding operation also not worked...

**Comment by Anduin2017** [comment]
Ok. let's keep this open. @hv0905  will keep investigating this. Thanks for your feedback!

**Comment by scottiiwei** [comment]
No worries. ^-^

**Comment by hv0905** [comment]
@scottiiwei Now everything should be fine again! In #625 I have changed our implementation of wide screen support. Trying the staging environment and tell us if the problem still exists. Thx.

**Comment by scottiiwei** [comment]
Tested via staging environment. Scrolling operation is worked now. Thank you for your patient:)

**Comment by Anduin2017** [comment]
Nice fix! @hv0905  Well done.

@scottiiwei  This fix will be deployed in several days. Thanks for your feedback!

Let's leave this issue open until we release the code to the production environment.
