### ISSUE TITLE
Kahla.App may send the same message twice in an unstable network.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#626]
## What do you suggest us to do?

Yesterday, while I was on the subway, with an unstable network. I tried sending messages with Kahla.

After I loaded the talking page, the network was unconnected. But I didn't notice this. And I sent 3 messages. They are all in sending mode.

But when I reconnect to the stable network, my partner told me that I sent the same message 3 times, which annoys him. And he asked me what's wrong with me.

## Additional context

Nothing.

![image](https://user-images.githubusercontent.com/19531547/62834454-3f470c00-bc7f-11e9-9cd4-fea48f20408c.png)

**Comment by jianba** [comment]
I also encountered the same problem and may have failed to send the message.
