### ISSUE TITLE
Consider refactor local search

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#629]
## What do you suggest us to do?
Now we use a standlond component to localsearch, this is unreasonable.

I suggest move the implementation to the friends component, just add a textbox above the list, like this:
![image](https://user-images.githubusercontent.com/29349119/62834103-64854b80-bc7a-11e9-8bba-fc6fb49f2c7c.png).

And also considering add a search for conversations (support searching last message).

## Additional context

Nothing.

**Comment by hv0905** [comment]
What's your idea? @Anduin2017 @xxyzz @Xiangrui2019

**Comment by Anduin2017** [comment]
I have another suggestion:

If I wanna search a conversation with the name: "一只特立独行的猪", I gonna search with the name "猪", and he is the only result. In this situation, I suggest pressing the enter button shall open the detail page with this user.

**Comment by Anduin2017** [comment]
Also, I mean, in the share component, there shall be a search function. Is there any solution that we can refactor all search, and create a `search-component` which can be used alongside all other components?

**Comment by Anduin2017** [comment]
If we can find a way to achieve all search function elegant and efficient, I strongly suggest refactoring this.

* Search bar in conversations(To search in messages)
* Search bar in friends(To search my conversations)
* Search bar in add new (To search new conversation)
* Search bar in share(To search in my conversations)

**Comment by Anduin2017** [comment]
Hi, @hv0905 , your new design is really nice!

It also solved a problem that when you press the back button on the old local search component and on a mobile device will accidentally quit Kahla!

How about the `share-target` component? Shall we add a search component here?
