### ISSUE TITLE
The app nav may display the item to one side

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#665]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging(Pre-release)`
- Last git commit: 90df87ae07c1ee08996ca3ae971c69c6fa6e770f
- Platform: `Web Desktop\Web Mobile\Electron\Cordova\PWA`
- Browser: `Edge Dev`

## How to repro

- Step 1: Go to one group
- Step 2: View group detail
- Step 3: Click `Share`

And then...

![image](https://user-images.githubusercontent.com/19531547/64469541-87662b00-d166-11e9-9889-f2c237597e0d.png)

It seems that this is not the only way to trigger this issue.

## Other information

Nothing.

**Comment by Anduin2017** [comment]
It seems that this issue happens on Chrome: 77.x and has been fixed in the newest canary build.

We have to wait until most of our users upgraded their Chrome to the latest (more than 78) version.

**Comment by hv0905** [comment]
chrome has released v78 in stable channel.
![image](https://user-images.githubusercontent.com/29349119/67399226-766e5d80-f5de-11e9-99d9-0c7f12858b63.png)

**Comment by Anduin2017** [comment]
Cool!
