### ISSUE TITLE
Better cache control required.

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#695]
## What do you suggest us to do?

Now we invalid all the caches per 20 mins. This can make the user always have the app up-to-date, but in slow network it takes a long time to load the app.
The reason why we use this cache cont is upgrading issue in android (#345).

We should use better solution (see below) to fix this problem and then remove the fuckin cache cont.

## Additional context
https://developers.google.com/web/fundamentals/integration/webapks#update-webapk
https://developers.google.com/web/updates/2019/06/webapk-update-frequency

**Comment by hv0905** [comment]
I think our service worker can manage cache correctly.
What about removing the 20-min-linit? @Anduin2017

**Comment by Anduin2017** [comment]
Do check twice on staging env.

**Comment by hv0905** [comment]
It seems that the auto-upgrade works correctly.
