### ISSUE TITLE
Strange reddot in south park.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#705]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: `dc0c2d0f635f664261fbe6973f571a3d5092f227`
- Platform: `Web Desktop\Web Mobile\Electron\PWA\TWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

- Step 1: Join group south-park

And then you will see the strange red dot without time limitaion:

![image](https://user-images.githubusercontent.com/19531547/66636050-01487300-ec43-11e9-98b7-c98d54dc5d7c.png)

## Expected situation

I expect that when there is a clock about the timer, always display the correct timer.

## Other information

Nothing.

**Comment by xxyzz** [comment]
You see, Kenny is the group owner. When he died, his soul will turn to that dot.
