### ISSUE TITLE
Possible to loose a message during sending messages.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#710]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging(Pre-release)\Production`
- Last git commit: `aaaaaa`
- Platform: `Web Desktop\Web Mobile\Electron\PWA\TWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

Currently, I do not know how to repro. But I have reproed this several times.

![image](https://user-images.githubusercontent.com/19531547/67001551-9d272280-f10c-11e9-97e6-cb135af110af.png)

## Expected situation

I expect that no matter what happened and what I send, no message will disappear.

## Other information

Nothing.

**Comment by Wenfengcheng** [comment]
Repro step:
When the previous message is in the sending state, sent the next message, and then the two message will be sent successfully, but the previous message will be removed.

**Comment by hv0905** [comment]
When the message is still in the `sending` state, it is just a `temp message` and will be removed when the next stargate event comes.
So if the stargate lost any message event, the issue might happened.

**Comment by Anduin2017** [comment]
While I couldn't find out why Stargate may lose message, can app-side changes make the temp message not just disappear or some other logic to judge if the message was sent?

**Comment by hv0905** [comment]
Way to repro steady:
1.go to a very slow network (`GFW` dalay is enough).
2.open kahla, then go to a conversation.
3.refresh by pressing F5.
4.while the conversation shows again, quickly type and send any message.(before the yellow bar disappear)
5.You can see the message always in `sending` status.

**Comment by hv0905** [comment]
It seems that the issue has been fixed.

**Comment by Anduin2017** [comment]
Nice! We shall keep testing this for at least 7 days before we release it to production.
