### ISSUE TITLE
Can not send image

### ISSUE THREAD

**Issue by mowatermelon** [AiursoftWeb/Kahla#717]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: ``
- Platform: `PWA`
- Browser: `Chrome`

## How to repro

- Step 1: choosing a friend dialog
- Step 2:  pasting a image
- Step 3:  the upload progress bar is stuck at 0,and get error log in console

![err log](https://probe.aiursoft.com/Download/Open/kahla-user-files/conversation-1999/2019-10-23/clipboardImg_1571812651329.png)

## Expected situation

image successfully uploaded

## Other information

Nothing.

**Comment by Anduin2017** [comment]
Will diagnose. Thanks for your feedback.

However, we couldn't repro by the info you mentioned and the image was successfully sent. Could you please fill more info about it?

**Comment by Anduin2017** [comment]
While we couldn't repro it, I guess it was an issue related to: 

https://en.wikipedia.org/wiki/Internet_censorship_in_China

But not related to this repro. So I gonna close it.
