### ISSUE TITLE
How to build and deploy Kahla to Cent OS?

### ISSUE THREAD

**Issue by litongjava** [AiursoftWeb/Kahla#731]
I wish to deploy Kahla in my corporate network. Could you please provide a tutorial? My OS is Cent OS-7.

**Comment by Anduin2017** [comment]
Please check wiki here: https://wiki.aiursoft.com/

![image](https://user-images.githubusercontent.com/19531547/68266885-6a2cda80-008b-11ea-8278-97903b02c269.png)
