### ISSUE TITLE
Friend request after accept may display wrong in app.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#739]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging(Pre-release) and Production`
- Last git commit: 7e01d0dedfe3c26e929166259b81a88b744e136e
- Platform: `Web Desktop\Web Mobile\Electron\PWA\TWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

- Step 1:  Sign in two accounts in two devices.
- Step 2:  From account A, send a friend request to account B. And keep looking at this page.
- Step 3:  In Account B, accept the friend request immediately.

And then in account A, the page still displays `Friend request sent` instead of `Message` even now B is already your friend. You still can't find account B in your friends and conversations.

## Expected situation

I expect that once B accepts A's request, the profile page shall allow A to talk to him immediately.

## Other information

Nothing.

**Comment by hv0905** [comment]
![image](https://user-images.githubusercontent.com/29349119/69881756-f1771200-1308-11ea-83a5-93b6c00cb38e.png)
After the `FriendAcceptedEvent` received, the `UserDetail` api still return `areFriends: false`, which is unreasonable and might be a bug.

**Comment by Anduin2017** [comment]
Ohh... That seems strange. I will diagnose.
