### ISSUE TITLE
A strange position of share button

### ISSUE THREAD

**Issue by ghost** [AiursoftWeb/Kahla#741]
It seems too big
![批注 2019-11-30 172325](https://user-images.githubusercontent.com/43675876/69898593-70fef280-1396-11ea-92ac-7d17af583923.png)

**Comment by Anduin2017** [comment]
So where shall we move this button?

**Comment by hv0905** [comment]
@Anduin2017 @xxyzz  Is it possible to move the menu to right-click (and/or) long-press menu?

**Comment by ghost** [comment]
Click the image to watch the fill size image, and long press to open a menu to share?
