### ISSUE TITLE
Support Microsoft YaHei font

### ISSUE THREAD

**Issue by EdiWang** [AiursoftWeb/Kahla#745]
## Chinese message font on HDPI screens can be enhanced

![image](https://user-images.githubusercontent.com/3304703/70033990-74d78280-15eb-11ea-86da-bfccb5af0c44.png)

Please add "Microsoft YaHei" to Kahla's font style.

```css
    font-family: whatever....,"Microsoft YaHei";
```

**Comment by EdiWang** [comment]
For legal information, please see https://www.zhihu.com/question/20882169

**Comment by Anduin2017** [comment]
Ohhh. Seems good. Under consideration.

**Comment by hv0905** [comment]
```
font-family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
```
This css set can make chinese font better in most platforms.
