### ISSUE TITLE
Add Forgive Green Theme

### ISSUE THREAD

**Issue by EdiWang** [AiursoftWeb/Kahla#746]
## Please add a green theme to honor programmers

Programmers are honest people and can get green easily. Green also means money for U.S., adding a green theme can benefit both Chinese programmers and U.S. people.

**Comment by Anduin2017** [comment]
Nice feature. Will resolve!

![image](https://user-images.githubusercontent.com/19531547/70035617-28da0d00-15ee-11ea-9588-12a07c03c548.png)
