### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by EdiWang** [AiursoftWeb/Kahla#747]
## Please make elements align

![image](https://user-images.githubusercontent.com/3304703/70036105-0bf20980-15ef-11ea-85e7-a472c53fd271.png)

![image](https://user-images.githubusercontent.com/3304703/70036114-11e7ea80-15ef-11ea-8a6f-b6a72165279d.png)

**Comment by Anduin2017** [comment]
Nice issue! Will resolve!

**Comment by Anduin2017** [comment]
@xxyzz Could you please fix this or making our grid design system better?

**Comment by Anduin2017** [comment]
Fixed.
