### ISSUE TITLE
All downloads return 404

### ISSUE THREAD

**Issue by JulianGmp** [AiursoftWeb/Kahla#753]
## What do you want to know?

I was curious about the project and wanted to download the windows client, but the download (https://download.kahla.app/Production/KahlaWindows/package.json/production/KahlaWindows/Kahla.Setup.3.8.4.exe) returns a 404.

## Describe alternatives you've considered

I've tried the downloads for other platforms as well, and they all seem to lead to a 404.

## Additional context

Nothing.

**Comment by Anduin2017** [comment]
So sorry about this. I've made a mistake. Sorry about that.

Now possible fixed. Please check again. Thanks!

**Comment by JulianGmp** [comment]
Windows downloads are working fine
the .deb package still returns a 404, while the rpm works
- https://download.kahla.app/production/KahlaLinux/kahla_3.8.4_amd64.deb
- https://download.kahla.app/production/KahlaLinux/kahla-3.8.4.x86_64.rpm

Maybe it's that underscore at `kahla_3.8.4`, since the other URL uses a hyphen

**Comment by Anduin2017** [comment]
The problem is that the `.deb` MIME type was treated as 'dangerous' file type on my web server.

I have fixed that. Thank you sooooo much for telling me this!
