### ISSUE TITLE
Groups display multiple duplicate messages

### ISSUE THREAD

**Issue by mentos33** [AiursoftWeb/Kahla#759]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: `b946b38`
- Kahla Version: 'v3.8.5'
- Platform: `Web Desktop`
- Browser: `Chrome\Edge\`

## How to repro

- Step 1: Sign in and join the group: Anduin-bilibili
- Step 2: Send or receive messages
- Step 3: 

![image](https://user-images.githubusercontent.com/47784076/71355216-55fc5880-25b9-11ea-9916-06d9149f927f.png)

![image](https://user-images.githubusercontent.com/47784076/71355283-817f4300-25b9-11ea-9975-ac32fb3917df.png)

![image](https://user-images.githubusercontent.com/47784076/71355394-e63a9d80-25b9-11ea-8249-92f642e8803a.png)

And then...Everyone in this group becomes a repeater.That's funny :)

## Expected situation

I expect that each message is displayed only once.

## Other information.

Sometimes twice, sometimes three times or more.

**Comment by Anduin2017** [comment]
Seems fixed.
