### ISSUE TITLE
Copy or drag files

### ISSUE THREAD

**Issue by xxyzz** [AiursoftWeb/Kahla#78]
**Is your feature request related to a problem? Please describe.**
Drag or copy files can send the message directly.

**Describe the solution you'd like**
https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/File_drag_and_drop

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by Anduin2017** [comment]
If I could paste an image to Kahla directly, that must be very helpful.
