### ISSUE TITLE
`Auto detect` theme support.

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#801]
## What do you suggest us to do?

As all we know, many modern web broswer like `chrome`  `Edge Chromium` or `safari` have a dark mode.

We can get that status to change kahla's theme automaticly.

## Additional context

https://twitter.com/levelsio/status/1089474045660155905

**Comment by Anduin2017** [comment]
Nice feature! Agree!

**Comment by Anduin2017** [comment]
I also want to change the theme of Kahla.Home with browser settings.
