### ISSUE TITLE
Rename every file sent as image or video

### ISSUE THREAD

**Issue by hv0905** [AiursoftWeb/Kahla#826]
## What do you suggest us to do?

1. When I sending an image or a video, I don't expect my file name was sent with the file itself. However, even if there is no file name displayed in the conversation. Other users can still find it in the url or the file history.
Maybe we should rename the image or video to a time tag one before uploading it.

2. When I was looking for file in the file history, I expect I can filter out the file sent as `file`, or sent as `image`. To do this, maybe we should add a `note` field in the probe file record.

## Additional context

Nothing.

**Comment by Anduin2017** [comment]
How about naming it as a GUID?
