### ISSUE TITLE
Use a better video player to play videos.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#830]
## What do you suggest us to do?

Now that we are using simple HTML5 video tag to play video. But the experience seems to be bad.

What about using VideoJs?

## Additional context

https://videojs.com/

**Comment by Anduin2017** [comment]
https://stackblitz.com/edit/angular-btj4zw

I guess this demo might be super helpful.

**Comment by hv0905** [comment]
It seems that it is a must to specific a video type when using videojs.
