### ISSUE TITLE
Connect to the new API changes

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#834]
https://github.com/AiursoftWeb/Kahla/pull/167

* [x] `NewFriendRequest` event will directly return the `Request` object
* [x] Refactored event `FriendAcceptedEvent`, renamed to `FriendsChangedEvent`. It will be triggered when any of your associated friend requests change, whether you sent it to you, whether it was approved or rejected
* [x] The `conversation/all` API will return the entity of the last message in this conversation and will carry the sender information
* [x] Refactored `WereDeletedEvent` and renamed it to `FriendDeletedEvent`. The deleted conversation ID will now be returned. And both the trigger person and the deleted person will push.
* [x] Added event type `GroupJoinedEvent`. Triggered when you join a group, it will return a `createdConversation`, a `messageCount`, a `latestMessage`.

To solve this issue, we need to modify the Kahla.App code to respect the new event logic.

**Comment by Anduin2017** [comment]
NewFriendRequest event will directly return the Request object.

This is helping the app to sync the friend requests locally.

**Comment by Anduin2017** [comment]
Refactored event FriendAcceptedEvent, renamed to FriendsChangedEvent. It will be triggered when any of your associated friend requests change, whether you sent it to you, whether it was approved or rejected

This is helping the app to create a new conversation when friend requests completed.

**Comment by Anduin2017** [comment]
The conversation/all API will return the entity of the last message in this conversation and will carry the sender information.

This is helping the app to sync the latest message so it can sync more messages based on WebSocket API without calling get messages.

**Comment by Anduin2017** [comment]
Refactored WereDeletedEvent and renamed it to FriendDeletedEvent. The deleted conversation ID will now be returned. And both the trigger person and the deleted person will push.

This is helping the app to delete the local conversation.

**Comment by Anduin2017** [comment]
Added event type GroupJoinedEvent. Triggered when you join a group, it will return a createdConversation, a messageCount, a latestMessage.

This is helping the app to create the local conversation when you joined a group even on another device.

**Comment by Anduin2017** [comment]
So, shall we close this? @hv0905

**Comment by hv0905** [comment]
ok
