### ISSUE TITLE
Disable notification feature.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#836]
## Describe the solution you'd like

When I logged in my Kahla account on multiple browsers, like both edge and chrome, when a new notification arrives, I will be notified twice. That is pretty annoying.

So I wish that I can disable one of the notifications.

## Describe alternatives you've considered

Currently, I have to disable it here. 

![image](https://user-images.githubusercontent.com/19531547/77221002-994a7100-6b80-11ea-9ade-54ddb4395aaa.png)

## Additional context

I wish there is a setting named `Show push notification`.

![image](https://user-images.githubusercontent.com/19531547/77221011-acf5d780-6b80-11ea-98d7-fac7e484b140.png)

By default, it is true.

If I disable this switch, My device will not be registered to the server so I won't receive any notification on this device.

This setting will not be synced to other devices.

**Comment by hv0905** [comment]
I think we should find a way to make the server not to push notification since if the service worker doesn't do anything when receive a push, an notification reads `This website is updating at the background` will be shown.

**Comment by Anduin2017** [comment]
OK. I will try to find a solution. Please wait.

**Comment by hv0905** [comment]
Maybe I have found some other way to disable it, I will try it tomorrow.

**Comment by Anduin2017** [comment]
I have developed a new API `dropDevice`.

Path: `/devices/dropdevice/{deviceId}`
Method: `HTTP POST`

### To get if current device enabled push notification

```javascript
IsElectron || serverReturnedDevices.Any(currentDeviceId)
```

### To disable push notification

```
Call drop device API and save the bool to local storage.
```

### To enable push notification

```
Cal add device API and save the bool to local storage.
```

### When app starts

```javascript
if (!electron) {
    var connected = serverReturnedDevices.Any(currentDeviceId);
    if (localstorage["EnablePush"] == true && !connected ) {
        AddCurrentDevice();
    }
    else if (localstorage["EnablePush"] == false && connected )) {
        DropCurrentDevice();
    }
}
```

`EnablePush` Shall be `true` by default.

@hv0905  how about this?

**Comment by Anduin2017** [comment]
Nice fix! @hv0905
