### ISSUE TITLE
Electron version of Kahla couldn't sign in a community server.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#843]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Staging(Pre-release)`
- Last git commit: 682e45efebbfb306071594569834e2ccd7c42e50
- Platform: `Electron`
- Browser: `Windows 10`

## How to repro

- Step 1:  Run `npm run electron` to start electron Kahla
- Step 2: Change server to `https://staging.server2.kahla.app`
- Step 3: Click the `Sign In` button.

And then the browser opened.

## Expected situation

I expect that the OAuth page shall be opened in electron.

## Other information

The bug is here:

https://github.com/AiursoftWeb/Kahla.App/blob/dev/src/index.js#L53

But I don't have a good idea to fix.

**Comment by hv0905** [comment]
I will try to fix it via IPC
