### ISSUE TITLE
One message will display multiple times.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#851]
[//]: <Don't delete any header! Please fill out the form or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Platform: `Web Desktop\Web Mobile\Electron\PWA\TWA`
- Browser: `Chrome\Edge\Firefox\Safari\Others`

## How to repro

We still can't find out how to repro this. But we are trying to investigate via reading the code.

![184F825AA40993DA3B9D67E094F0CF8C](https://user-images.githubusercontent.com/19531547/78109323-8b6fd800-742b-11ea-95f0-2c35dbba2092.png)

**Comment by hv0905** [comment]
When the next time you run into this bug, pls copy the localstorage cache of the conversation in F12. This might help us resolve the bug.
