### ISSUE TITLE
Is this an issue that because of wrong calculation?

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/Kahla#875]
## What do you want to know?

![image](https://user-images.githubusercontent.com/19531547/80799849-8644ab00-8bda-11ea-82e9-2e1b5891730c.png)

## Describe alternatives you've considered

I guess both sides of large emoji shall display the same color

## Additional context

Nothing.

**Comment by hv0905** [comment]
In fact, only colored emoji should be shown in this way. 🤣
