### ISSUE TITLE
I cant change/upload profile picture ?

### ISSUE THREAD

**Issue by ghost** [AiursoftWeb/Kahla#880]
The app stop here:
![fix_2](https://user-images.githubusercontent.com/64690726/81320375-b5ce3a00-9056-11ea-9fe7-900cbd98d8fc.PNG)
![fix](https://user-images.githubusercontent.com/64690726/81320390-bb2b8480-9056-11ea-82b8-ef67279e445a.PNG)

**Comment by Anduin2017** [comment]
Cloud you please share us the error logs by pressing F12 and view the console tab?

**Comment by ghost** [comment]
![vbtrhtbrnm4](https://user-images.githubusercontent.com/64690726/81328883-41e65e80-9063-11ea-8b41-fada1547768c.PNG)

This happened after update from 4.0.1 to 4.1.0

**Comment by Anduin2017** [comment]
Hi! Thanks for your info! We have reproduced this issue. It was because of a low layer API breaking change. We will fix this as soon as possible.

**Comment by Anduin2017** [comment]
We have patched a hotfix. It seems the problem shall be disappeared. Please help us test it and close this issue if it is not happening again.

Thanks for your feedback and sorry for your inconvenience.

**Comment by ghost** [comment]
Thanks to you.. really great app... problem fixed

Not very important:
Seems this app can actually beat "Discord" which has no privacy
I think (im from latin america) that "Kahla" name sounds rare/unfamiliar in english language
and some people feels insecure only by that.

**Comment by Anduin2017** [comment]
The word `Kahla` officially reads like `/ˈKɑ:lɑ/`
