### ISSUE TITLE
ICON issue

### ISSUE THREAD

**Issue by jyxjjj** [AiursoftWeb/Kahla#894]
Sincerely suggest that you should modify the organization icon, organization name, application icon, application name. They are copyrights to Blizzard Entertainment @Blizzard . Github follows DMCA.

**Comment by Anduin2017** [comment]
Before developing this, we have verified that, aiursoft and kahla was not registered trademark.

**Comment by jyxjjj** [comment]
trademark and Design is different , they designed.
[blizzard-end-user-license-agreement](https://www.blizzard.com/en-us/legal/fba4d00f-c7e4-4883-b8b9-1b4500a402ea/blizzard-end-user-license-agreement)
Parts:
<blockquote>
Blizzard’s Ownership

With the sole exception of the Licensors’ Games, Blizzard is the owner or licensee of all right, title, and interest in and to the Platform, including the Games that are produced and developed by Blizzard (“Blizzard Games”), Custom Games derived from a Blizzard Game, Accounts, and all of the features and components thereof. The Platform may contain materials licensed by third-parties to Blizzard, and these third-parties may enforce their ownership rights against you in the event that you violate this Agreement.  The following components of the Platform (which do not include content or components of the Licensors’ Games), are owned or licensed by Blizzard:

All virtual content appearing within the Platform, including the Blizzard Games, such as:

Visual Components: Locations, artwork, structural or landscape designs, animations, and audio-visual effects;

Narrations: Themes, concepts, stories, and storylines;

Characters: The names, likenesses, inventories, and catch phrases of Game characters;

Items: Virtual goods, such as digital cards, currency, potions, weapons, armor, wearable items, skins, sprays, pets, mounts, etc.;  
</blockquote>
And so on.

**Comment by Anduin2017** [comment]
I reopen this, for we need to register kahla and aiursoft trademark in the future to avoid further conflict.

Or once Kahla and aiursoft design were registered or verified to be registered, we will change it immediately.

**Comment by jyxjjj** [comment]
Seems you are lucky that Blizzard the whole company is going to closed. 🤣
