### ISSUE TITLE
卡拉网页端关于 Unicode 导致的问题

### ISSUE THREAD

**Issue by Perlistan** [AiursoftWeb/Kahla#945]
[//]: <Don't delete any header! Please fill out the form, or your bug report will not be considered!> 

## Environment

- Environment: `Production`
- Last git commit: `null`
- Platform: `Web Desktop\Web Mobile`
- Browser: `Chrome`

## How to repro

- Step 1: 在任何一个聊天框中输入单个字符加任意 Unicode 都会让该字符变大
- Step 2: 使用例如【U+200B】的 Unicode 会导致聊天气泡消失并成功发送
- Step 3: 使用倒序字符 Unicode 加工用户名会导致其他人 @ 你的时候发生奇妙的事情

## Expected situation

经测试涉及 Unicode 类型较多，建议使用正则判断合法性

## Other information

Nothing.

**Comment by Anduin2017** [comment]
By design.
